# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
  end

  config.ssh.insert_key = false

  cluster = {
    "reg" =>  { :ip => "192.168.33.110", :mem => 512,  :cpu => 1 },
    "misc" => { :ip => "192.168.33.111", :mem => 512,  :cpu => 1 },
    "m1" =>  { :ip => "192.168.33.121", :mem => 512,  :cpu => 1 },
    "m2" =>  { :ip => "192.168.33.122", :mem => 512,  :cpu => 1 },
    "m3" =>  { :ip => "192.168.33.123", :mem => 512,  :cpu => 1 },
    "s1" =>  { :ip => "192.168.33.131", :mem => 1024, :cpu => 2 },
    "s2" =>  { :ip => "192.168.33.132", :mem => 1024, :cpu => 1 },
    "s3" =>  { :ip => "192.168.33.133", :mem => 1024, :cpu => 1 }
  }

  cluster.each_with_index do | (hostname, info), index |
    # config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define hostname do | host |
      host.vm.box = "centos7"
      host.vm.provider "virtualbox" do |v|
        v.name   = "kubernetes-#{hostname}"
        v.memory = info[:mem]
        v.cpus   = info[:cpu]
      end
      host.vm.hostname = hostname
      host.vm.network "private_network", ip: info[:ip]
      # if index == cluster.size - 1
      #   config.vm.provision :ansible do |ansible|
      #     # Disable default limit to connect to all the machines
      #     ansible.limit = 'all'
      #     ansible.playbook = "provisioning/playbook.yml"
      #     ansible.inventory_path = "ansible_inventory"
      #   end
      # end
    end
  end

  config.vm.box_check_update = false
end
