# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
  end

  config.ssh.insert_key = false

  cluster = {
    "c1" => { :ip => "192.168.33.85", :mem => 512,  :cpu => 1 },
    "c2" => { :ip => "192.168.33.86", :mem => 512,  :cpu => 1 }
  }

  cluster.each_with_index do | (hostname, info), index |
    config.vm.define hostname do | host |
      host.vm.box = "centos7"
      host.vm.provider "virtualbox" do |v|
        v.name   = "ceph-#{hostname}"
        v.memory = info[:mem]
        v.cpus   = info[:cpu]
        disk = "./disk_#{hostname}.vdi"

        unless File.exist?(disk)
          v.customize ['createhd', '--filename', disk, '--size', 1 * 1024]
        end
        v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
      end


      host.vm.hostname = hostname
      host.vm.network "private_network", ip: info[:ip]
      # if index == cluster.size - 1
      #   config.vm.provision :ansible do |ansible|
      #     # Disable default limit to connect to all the machines
      #     ansible.limit = 'all'
      #     ansible.playbook = "provisioning/playbook.yml"
      #     ansible.inventory_path = "ansible_inventory"
      #   end
      # end
    end
  end

  config.vm.box_check_update = false
end
